[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Silecarf-SE <silecarf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
geopy = "^1.21"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
